apiVersion: addons.productive-k3s.io/v1
kind: Addon
metadata:
  name: openship-whoami-redis-web
  version: 0.1.0
  category: generated
spec:
  type: helm
  impact:
    cluster: true
    host: false
    summary: Generated component 'web' from docker-compose source.
  configure:
    script: scripts/configure.sh
  install:
    script: scripts/install.sh
  validate:
    script: scripts/validate.sh
  clean:
    script: scripts/clean.sh
  backup:
    script: scripts/backup.sh
  productiveK3s:
    exposure:
      public:
        mode: clusterip
        namespace: pk3s-openship-whoami-redis
        service:
          name: web
          port: 8080
