applicationName: web
deployment:
  enabled: true
  replicas: 1
  image:
    repository: traefik/whoami
    tag: v1.10
  env:
    APP_ENV:
      value: production
    REDIS_HOST:
      value: cache
  ports:
  - name: port-80
    containerPort: 80
    protocol: TCP
service:
  enabled: true
  ports:
  - name: port-80
    port: 8080
    targetPort: 80
    protocol: TCP
