apiVersion: addons.productive-k3s.io/v1
kind: Addon
metadata:
  name: registry
  version: 0.1.0
  category: platform
spec:
  type: shell
  configure:
    script: scripts/configure.sh
  install:
    script: scripts/install.sh
  validate:
    script: scripts/validate.sh
  clean:
    script: scripts/clean.sh
  backup:
    script: scripts/backup.sh
