apiVersion: addons.productive-k3s.io/v1
kind: Stack
metadata:
  name: base
  version: 0.1.0
  sourceRevision: development
spec:
  compatibility:
    requires:
      core:
        contract: artifact/v1
        minVersion: 0.9.6
        maxVersionExclusive: 0.10.0
      kubernetes:
        distros:
          - k3s
          - rke2
  resolution:
    mode: catalog

  addons:
    - cert-manager
    - longhorn
    - rancher
    - registry
